version: "3.8"
services:
  mysql_db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=alami_sharia
      - MYSQL_USER=root
    volumes:
      - ./alami_sharia:/var/lib/mysql
      - ./data/alami_sharia.sql:/docker-entrypoint-initdb.d/init.sql
  alami_sharia_spring:
    image: alami_sharia_spring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/alami_sharia?serverTimezone=UTC
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql_db